### PR TITLE
fix: filter non-Anthropic content blocks before sending to Vertex API

### LINKED ISSUE #9583: [BUG] Input tag 'reasoning' found using 'type' does not match any of the expected tags on Claude Sonnet 4.5
### Problem (one or two sentences)

Persistent error started happening lately: `Input tag 'reasoning' found using 'type' does not match any of the expected tags`

### Context (who is affected and when)

I think it happens when the context is starting to fill up >70%. Doesnot matter if reasoning is enabled or disabled.

Reported here as well: https://github.com/RooCodeInc/Roo-Code/issues/9392#issuecomment-3576388290

### Reproduction steps

1) Do the agent stuff on new session
2) When context fills up to about 160k/200k tokens you may see the error

### Expected result

Message should be correct and accepted by API

### Actual result

Error is shown. Can't be retried. New session is the only way to continue.

### Variations tried (optional)

_No response_

### App Version

3.34.3

### API Provider (optional)

Google Vertex AI

### Model Used (optional)

Claude Sonnet 4.5

### Roo Code Task Links (optional)

_No response_

### Relevant logs or errors (optional)

```shell
400 {"type":"error","error":{"type":"invalid_request_error","message":"messages.1.content.0: Input tag 'reasoning' found using 'type' does not match any of the expected tags: 'document', 'image', 'redacted_thinking', 'search_result', 'text', 'thinking', 'tool_result', 'tool_use'"},"request_id":"req_vrtx_011CVUxYcMYbPv2DnWqqt7nb"}
```

### PR DESCRIPTION
**Pull request by hannesrudolph**
## Summary
Fixes the context condensation error when using reasoning with Anthropic models on Vertex:
```
Input tag 'reasoning' found using 'type' does not match any of the expected tags
```

## Root Cause
1. Roo Code stores reasoning content internally with `type: 'reasoning'` (provider-agnostic format)
2. Gemini stores thought signatures with `type: 'thoughtSignature'`
3. When messages are replayed to Anthropic/Vertex APIs during context condensation or model switching, these non-standard types cause 400 errors

## Solution
Added `filterNonAnthropicBlocks()` to both `anthropic-vertex.ts` and `anthropic.ts` handlers that uses an **allowlist approach** to only keep valid Anthropic content types.

**Valid Anthropic content types (allowlist):** `text`, `image`, `tool_use`, `tool_result`, `thinking`, `redacted_thinking`, `document`

This automatically filters out:
- `type: 'reasoning'` - Internal Roo Code format
- `type: 'thoughtSignature'` - Gemini's encrypted reasoning signature
- Any other unknown/future block types

## Implementation Details
This follows established patterns in the codebase:
- **Gemini handler** (line 98-104): Filters `type: 'reasoning'` messages
- **gemini-format.ts** (line 131-136): Skips unsupported blocks with console.warn
- **Claude Code handler**: Uses `filterMessagesForClaudeCode()` for image blocks
- **Cerebras handler**: Strips thinking tokens from assistant messages

## Testing
- Added tests for filtering internal reasoning blocks
- Added tests for filtering empty messages after removing all reasoning blocks
- Added test for filtering unknown future block types
- All 48 tests pass

## Related
Fixes #9583
Related to #9584

### CODE REVIEW

**Comment by ghost** [comment]
> **Oroocle**  Clock &nbsp;&nbsp;[Follow along on Roo Cloud](https://app.roocode.com/cloud-jobs/YeSMPOKB?utm_source=github-comment&utm_medium=link&utm_campaign=github.pr.review.sync)

Review complete. One issue was flagged related to Anthropic prompt caching model coverage.

- [x] Ensure `claude-opus-4-5-20251101` is included in the prompt-caching switch and beta-header logic in `src/api/providers/anthropic.ts` so it uses the same caching behavior as the other Opus models.

> <details>
> <summary>Previous reviews</summary>
> 
> - db4448f: [Review #1](https://app.roocode.com/cloud-jobs/D2K6bRqa?utm_source=cloud-job-url&utm_medium=link&utm_campaign=previous-reviews)
> - c810bc5: [Review #2](https://app.roocode.com/cloud-jobs/ihkjXox1?utm_source=cloud-job-url&utm_medium=link&utm_campaign=previous-reviews)
> - d465146: [Review #3](https://app.roocode.com/cloud-jobs/Oxvw7rV0?utm_source=cloud-job-url&utm_medium=link&utm_campaign=previous-reviews)
> </details>
<sub>Mention @roomote in a comment to request specific changes to this pull request or [fix all unresolved issues](https://app.roocode.com/fix-issues?repo=RooCodeInc/Roo-Code&prNumber=9618&commentId=3582575280).</sub>

File: src/api/providers/anthropic.ts [hunk 1]
```diff
@@ -56,7 +107,6 @@ export class AnthropicHandler extends BaseProvider implements SingleCompletionHa
 		switch (modelId) {
 			case "claude-sonnet-4-5":
```
Comment (ghost) [inline src/api/providers/anthropic.ts:61]: `claude-opus-4-5-20251101` is defined in `anthropicModels` with `supportsPromptCache: true`, but it is missing from this prompt-caching switch so it will fall back to the non-caching path and not send the `prompt-caching-2024-07-31` beta header. If this model is expected to support prompt caching like the other Opus variants, it should be added to both the outer switch and the inner header switch.

<sub>[Fix it with Roo Code](https://app.roocode.com/fix-issue/?repo=RooCodeInc/Roo-Code&prNumber=9618&fixId=91b96148a5) or mention @roomote and request a fix.</sub>

File: src/api/transform/anthropic-filter.ts [hunk 2]
```diff
@@ -0,0 +1,47 @@
+import { Anthropic } from "@anthropic-ai/sdk"
+
+/**
+ * List of content block types that are NOT valid for Anthropic API.
+ * These are internal Roo Code types or types from other providers (e.g., Gemini's thoughtSignature).
+ * Valid Anthropic types are: text, image, tool_use, tool_result, thinking, redacted_thinking, document
```
Comment (mrubens) [inline src/api/transform/anthropic-filter.ts]: Should we make this an allowlist instead of a denylist?

**Comment by cardil** [comment]
**:tada: Confirmed.**

After upgrading to [v3.34.6](https://github.com/RooCodeInc/Roo-Code/releases/tag/v3.34.6) I was able to resume the previously failing thread, and it properly condenses.

Screenshot From 2025-11-27 01-08-30
