### PR TITLE
fix(mention): conditionally remove aftercursor content

### LINKED ISSUE #2286: Lost typyed content after insert @
### App Version

3.11.4

### API Provider

VS Code LM API

### Model Used

Claude 3.7 Sonnet

### Actual vs. Expected Behavior

After I type in some conten and try to add a '@' in the beginning, everything lost after the '@'. Even ctrl+z can't recover

### Detailed Steps to Reproduce

1.Type something
2.Move cursor to the beginning
3.Insert a '@'

### Relevant API Request Output

```shell

```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by elianiva**
## Context

This fixes #2286

Currently we're removing every content after the cursor position, which might be ideal for the case where the cursor is in the middle of mention

```
@/path/to|/foo
         ^ cursor here
```

but this becomes an issue when the content after the cursor is the user's prompt using languages that don't require space for its word boundary (chinese, japanese, korean, etc)
so it removes everything

```
@/path/to/foo|テキスト。。。
             ^ cursor here

// current behaviour
@/path/to/foo.ts

// after this PR
@/path/to/foo.ts テキスト。。。
```

## Implementation

The current implementation simply checks if the content after the cursor is latin alphanumeric using `[a-zA-Z0-9\s]` regex.
If it passes, meaning that it's most likely a path--since using non-latin letters for filename / directory is very uncommon, i think this heuristic is okay--then it will replace everything, otherwise it will just append the content and prepend a space.

### Before
https://github.com/user-attachments/assets/7ba24551-eb83-4dd0-ad3d-b4193e8afd3a

### After
https://github.com/user-attachments/assets/6958885f-22e2-430e-a947-36b8ace52ba2

## How to Test

Reproduce what I did on the video above.

## Get in Touch

my discord handle is @elianiva on roocode discord server

----

> [!IMPORTANT]
> Fixes issue #2286 by modifying `insertMention()` in `context-mentions.ts` to conditionally retain non-latin content after the cursor.
> 
>   - **Behavior**:
>     - Modify `insertMention()` in `context-mentions.ts` to conditionally retain content after cursor if non-latin characters are detected.
>     - Uses regex `/^[a-zA-Z0-9\s]*$/` to check if `afterCursor` is alphanumeric.
>     - Appends content with a space if non-alphanumeric, otherwise replaces it.
>   - **Misc**:
>     - Fixes issue #2286 related to handling non-latin scripts in mentions.
> 
> <sup>This description was created by </sup>[Ellipsis](https://www.ellipsis.dev?ref=RooVetGit%2FRoo-Code&utm_source=github&utm_medium=referral)<sup> for c26d003bb5b71dd24a38edc5dc84d3af1f54e756. It will automatically update as commits are pushed.</sup>

### CODE REVIEW

**Review by cte — APPROVED** [review]

File: webview-ui/src/utils/context-mentions.ts [hunk 1]
```diff
@@ -33,7 +33,12 @@ export function insertMention(
 	if (lastAtIndex !== -1) {
 		// If there's an '@' symbol, replace everything after it with the new mention
 		const beforeMention = text.slice(0, lastAtIndex)
-		newValue = beforeMention + "@" + value + " " + afterCursor.replace(/^[^\s]*/, "")
+		// Only replace if afterCursor is all alphanumerical
+		// This is required to handle languages that don't use space as a word separator (chinese, japanese, korean, etc)
+		const afterCursorContent = /^[a-zA-Z0-9\s]*$/.test(afterCursor)
+			? afterCursor.replace(/^[^\s]*/, "")
+			: afterCursor
+		newValue = beforeMention + "@" + value + " " + afterCursorContent
```
Comment (mrubens) [inline webview-ui/src/utils/context-mentions.ts:41]: I don't know that I see why this replacing is necessary at all. What's the downside of just always doing `newValue = beforeMention + "@" + value + " " + afterCursor`?

Comment (elianiva) [reply webview-ui/src/utils/context-mentions.ts:41]: my best guess would be for this case (hope this makes sense)

suppose that we have this scenario for the prompt

```
@/src/pages/feature-a|/index.jsx implement something for this page
                     ^ cursor position
```

with the current code, when the user choose other folder, such as `feature-b` and then press enter, it will be replaced as

```
@/src/pages/feature-b/index.jsx| implement ...
                               ^ cursor position
```

if we don't do the replacement, we'll end up with


```
@/src/pages/feature-b/index.jsx|/index.jsx implement ...
                               ^ cursor position
```

i'm not sure if i like this behaviour either, i'm planning to simplify the display so that it will only show folder name for folders and filename for files, just like how cursor does it

most of the time you'll remove the full path and start over with the mention anyway, and it gets pretty long on the prompt UI if you include a lot of files

so instead of this

```
@/src/pages/feature-b/index.jsx implement this feature
```

we'll have something like this instead

```
[index.jsx] implement this feature
^ an actual box, not [] character
```

so in the case of longer contexts, instead of this:

```
@/src/pages/feature-b/index.jsx implement @/src/components/card.tsx to handle data coming from @/src/services/data.ts
```

we'll have this instead

```
[index.jsx] implement [card.tsx] to handle data coming from [data.ts]
```

and the current behaviour of the infix-cursor-word-replacement would be no longer needed
