### PR TITLE
fix: prevent context condensing on settings save when provider/model unchanged

### LINKED ISSUE #4430: [BUG] Context condensing triggers on settings Save during active task
## Type
Bug

## Problem
Saving settings during an active task immediately triggers context compression, even when the configured threshold is 100%.

## Context
This affects users running long, read-heavy tasks. When the settings view is opened and Save is clicked during an active task, a context compression event occurs right away and the context shrinks, despite the context bar being well below the threshold. Environment example: GPT‑4.1 via OpenRouter with “Multi-file read (experimental)” enabled.

## Reproduction
1) Set your model to GPT‑4.1 with OpenRouter provider
2) Enable “Multi-file read (experimental)” in settings
3) Set context compression threshold to 100%
4) Start a new task in a workspace with a good amount of code
5) Enter the prompt: `read 10 files at a time 8 times in a row`
6) While the task is running and the context bar is increasing, open the settings view
7) Toggle any setting back and forth to activate the Save button (without actually changing any setting)
8) Click Save
9) Observe that context compression triggers immediately, regardless of actual context usage

## Expected result
Context compression should only trigger when the configured threshold is reached (100% in this case). Saving settings during an active task should not cause compression by itself.

## Actual result
Context compression triggers immediately upon saving settings during an active task, even when context usage is well below the threshold.

### PR DESCRIPTION
**Pull request by daniel-lxs**
## Problem

Fixes #4430

When clicking Save in Settings during an active task, context condensing would trigger immediately even when the configured threshold was 100%. This happened because the extension unconditionally rebuilt the running task's API handler, causing transient changes to model metadata (contextWindow, maxTokens) which triggered the `allowedTokens` fast-path in context condensing logic.

## Root Cause

The issue was NOT about UI component unmounting or model info flicker (PR #9101). The actual problem:

1. Settings Save calls `upsertProviderProfile` or `activateProviderProfile`
2. These methods unconditionally rebuilt the API handler: `task.api = buildApiHandler(providerSettings)`
3. Rebuilding updates model metadata even when provider/model unchanged
4. Context condensing has two triggers:
   - `contextPercent >= threshold` (user's 100% setting)
   - `prevContextTokens > allowedTokens` (fast-path based on contextWindow/maxTokens)
5. Transient metadata changes triggered the fast-path, causing immediate condensing regardless of threshold

## Solution

Added guards in both methods to only rebuild the API handler when provider OR model ID actually changes:

```typescript
if (task && task.apiConfiguration) {
    const currentProvider = task.apiConfiguration.apiProvider
    const newProvider = providerSettings.apiProvider
    const currentModelId = getModelId(task.apiConfiguration)
    const newModelId = getModelId(providerSettings)

    if (currentProvider !== newProvider || currentModelId !== newModelId) {
        task.api = buildApiHandler(providerSettings)
    }
}
```

## Changes

- Added `getModelId` import to ClineProvider
- Added guard in `upsertProviderProfile` to prevent unnecessary handler rebuilds
- Added guard in `activateProviderProfile` to prevent unnecessary handler rebuilds
- Added comprehensive test suite (9 tests, all passing) to verify behavior

## Testing

- ✅ Handler NOT rebuilt when provider/model unchanged (fixes #4430)
- ✅ Handler IS rebuilt when provider changes
- ✅ Handler IS rebuilt when model changes
- ✅ No errors when no task is running
- ✅ All existing tests pass (310 test files, 4022 tests)

## Impact

This targeted fix prevents the "condense on save" behavior while preserving handler rebuilds when genuinely needed (provider or model change).

----

> [!IMPORTANT]
> Fixes unnecessary context condensing by ensuring API handler rebuilds only on provider/model changes in `ClineProvider`.
> 
>   - **Behavior**:
>     - Prevents unnecessary context condensing by only rebuilding API handler if provider or model changes in `ClineProvider`.
>     - Fixes issue #4430 where context condensing triggered on settings save even with 100% threshold.
>   - **Code Changes**:
>     - Adds `updateTaskApiHandlerIfNeeded()` in `ClineProvider` to check for provider/model changes before rebuilding.
>     - Modifies `upsertProviderProfile` and `activateProviderProfile` to use the new guard.
>   - **Testing**:
>     - Adds `ClineProvider.apiHandlerRebuild.spec.ts` with 9 tests to verify handler rebuild logic.
>     - Tests ensure handler is rebuilt only when provider or model changes, and not when unchanged.
>     - Confirms no errors occur when no task is running.
> 
> <sup>This description was created by </sup>[Ellipsis](https://www.ellipsis.dev?ref=RooCodeInc%2FRoo-Code&utm_source=github&utm_medium=referral)<sup> for 5a2be5b84f2971588f027a0765e3c9d093c66d83. You can [customize](https://app.ellipsis.dev/RooCodeInc/settings/summaries) this summary. It will automatically update as commits are pushed.</sup>

### CODE REVIEW

**Comment by ghost** [comment]
> **Rooviewer**  Clock &nbsp;&nbsp;[See task on Roo Cloud](https://app.roocode.com/cloud-jobs/qjVtg3vm?utm_source=github-comment&utm_medium=link&utm_campaign=github.pr.review.sync)

Review complete. Code duplication successfully resolved with clean DRY refactoring. No new issues found.

- [x] Guard logic incorrectly handles `undefined` model IDs, causing unnecessary rebuilds when comparing `undefined !== "model"` evaluates to `true`

> <details>
> <summary>Previous reviews</summary>
> 
> - eabaaa6: [Review #1](https://app.roocode.com/cloud-jobs/LXdkOCiy?utm_source=cloud-job-url&utm_medium=link&utm_campaign=previous-reviews)
> - b39308c: [Review #2](https://app.roocode.com/cloud-jobs/BeX1lA3W?utm_source=cloud-job-url&utm_medium=link&utm_campaign=previous-reviews)
> </details>
<sub>Mention @roomote in a comment to request specific changes to this pull request or [fix all unresolved issues](https://app.roocode.com/fix-issues?repo=RooCodeInc/Roo-Code&prNumber=9108&commentId=3505597924).</sub>

**Comment by daniel-lxs** [comment]
## Review Response

**@ellipsis-dev comment**: FIXED - Updated test to capture original API reference and assert against it instead of self-comparison.

**@roomote comment**: INCORRECT - The current logic handles all cases correctly:

### Why roomote's suggestion would break the fix:

**Current logic** (`currentModelId !== newModelId`):
- Both undefined: `undefined !== undefined` → `false` → No rebuild (correct)
- Both same: `"gpt-4" !== "gpt-4"` → `false` → No rebuild (correct)  
- Different: `"gpt-4" !== "claude"` → `true` → Rebuild (correct)
- **User selects model**: `undefined !== "gpt-4"` → `true` → Rebuild (correct - NEW model selected!)
- **User clears model**: `"gpt-4" !== undefined` → `true` → Rebuild (correct - model REMOVED!)

**Roomote's suggested logic** (`currentModelId !== undefined && newModelId !== undefined && currentModelId !== newModelId`):
- Both undefined: Skip check → No rebuild (correct by accident)
- Both same: `"gpt-4" !== "gpt-4"` → `false` → No rebuild (correct)
- Different: `"gpt-4" !== "claude"` → `true` → Rebuild (correct)
- **User selects model**: `undefined !== undefined` fails first check → **No rebuild (BUG! Should rebuild)**
- **User clears model**: `"gpt-4" !== undefined` fails second check → **No rebuild (BUG! Should rebuild)**

### The undefined transitions ARE valid model changes:
- Selecting a model (undefined → "gpt-4") changes the effective model used by the task
- Clearing a model ("gpt-4" → undefined) also changes it
- Both require handler rebuild to reflect the new model metadata

The current implementation is correct. All tests pass including the new comprehensive test suite.

File: src/core/webview/ClineProvider.ts [hunk 1]
```diff
@@ -1344,7 +1345,19 @@ export class ClineProvider
...
+					// Only rebuild API handler if provider or model actually changed
+					// to avoid triggering unnecessary context condensing
+					const currentProvider = task.apiConfiguration.apiProvider
+					const newProvider = providerSettings.apiProvider
+					const currentModelId = getModelId(task.apiConfiguration)
+					const newModelId = getModelId(providerSettings)
+
+					if (currentProvider !== newProvider || currentModelId !== newModelId) {
+						task.api = buildApiHandler(providerSettings)
+					}
```
[the remark this answers is not in the document]
Comment (daniel-lxs) [reply src/core/webview/ClineProvider.ts]: https://github.com/RooCodeInc/Roo-Code/pull/9108#issuecomment-3505621968

**Comment by ghost** [comment]
> **Fixaroo**  Clock &nbsp;&nbsp;[See task on Roo Cloud](https://app.roocode.com/cloud-jobs/epSqfIvt?utm_source=github-comment&utm_medium=link&utm_campaign=github.pr.comment.respond)

## Analysis Complete: PR Author Is Correct

After thorough analysis of the guard logic and the `getModelId` implementation, **the PR author's response is accurate and no changes are needed**.

### The Guard Logic Is Correct

The current implementation:
```typescript
if (currentProvider !== newProvider || currentModelId !== newModelId) {
    task.api = buildApiHandler(providerSettings)
}
```

### Why `undefined` Transitions Are Valid Model Changes

The `getModelId` function returns `string | undefined`:
```typescript
export const getModelId = (settings: ProviderSettings): string | undefined => {
	const modelIdKey = modelIdKeys.find((key) => settings[key])
	return modelIdKey ? settings[modelIdKey] : undefined
}
```

**All scenarios work correctly:**

1. ✅ **Both undefined**: `undefined !== undefined` → `false` → No rebuild (correct)
2. ✅ **Both same**: `"gpt-4" !== "gpt-4"` → `false` → No rebuild (correct)
3. ✅ **Different models**: `"gpt-4" !== "claude"` → `true` → Rebuild (correct)
4. ✅ **User selects model**: `undefined !== "gpt-4"` → `true` → **Rebuild (correct!)**
5. ✅ **User clears model**: `"gpt-4" !== undefined` → `true` → **Rebuild (correct!)**

### Why The Reviewer's Concern Is Unfounded

The reviewer's suggested check for `undefined` would **break scenarios 4 and 5**, where:
- A user selects a model for the first time (`undefined` → `"gpt-4"`)
- A user clears their model selection (`"gpt-4"` → `undefined`)

Both are legitimate model changes that require rebuilding the API handler to reflect the new configuration.

### Conclusion

The PR correctly fixes issue #4430 by preventing unnecessary API handler rebuilds when the provider and model haven't actually changed, while still rebuilding when they do change (including transitions to/from `undefined`). The implementation is sound and all tests pass.

**No code changes required.**

File: src/core/webview/ClineProvider.ts [hunk 2]
```diff
@@ -1405,7 +1418,19 @@ export class ClineProvider
...
+			const currentModelId = getModelId(task.apiConfiguration)
+			const newModelId = getModelId(providerSettings)
+
+			if (currentProvider !== newProvider || currentModelId !== newModelId) {
+				task.api = buildApiHandler(providerSettings)
+			}
+		} else if (task) {
+			// Fallback: rebuild if apiConfiguration is not available
 			task.api = buildApiHandler(providerSettings)
 		}
```
Comment (mrubens) [inline src/core/webview/ClineProvider.ts]: This code is the same as above - can we move it into a shared method?

Comment (mrubens) [reply src/core/webview/ClineProvider.ts]: @roomote can you address this?
