### PR TITLE
Fix input box revert issue and configuration loss during profile switch #955

### LINKED ISSUE #955: [FATAL] All input boxes are broken, not just ollama or lmstuido
### Which version of the app are you using?

v3.3.17

### Which API Provider are you using?

OpenAI Compatible

### Which Model are you using?

any

### What happened?

All input boxes will lose data when the input speed is too fast, and the model configurations will overwrite each other when switching between profiles.
I see that #931 only modifies the code related to ollama and lmstudio. Are you sure these modifications can fix all input boxes?
In fact, there are problems with the configuration input boxes of all providers, and the configuration profile is completely unusable.

### Steps to reproduce

The following two operations can reproduce the fault

* Quickly type in multiple inputs/checkboxes.
* Switching between multiple profiles.

### Relevant API REQUEST output

```shell

```

### Additional context

* Considering that this issue is so widespread, the settings menu may need to be reworked.
* This issue is somewhat similar to #257. I am not sure whether the wrong value displayed in the settings will become the actual value of the configuration.

https://github.com/user-attachments/assets/db72e618-a2e0-42b5-aceb-c68995a2a6e2

https://github.com/user-attachments/assets/4655b2c7-d185-4a62-a7ba-b9ab357d8fd5

### PR DESCRIPTION
**Pull request by System233**
Fixes #955

## Description

This PR made the following changes:

1. Added a saveApiConfiguration operation to provide a configuration save function without forced UI updates.

2. handleInputChange uses saveApiConfiguration to save to avoid overwriting user input when quickly switching input boxes

3. Merge a large number of async calls in updateApiConfiguration to reduce the time consumption of upsertApiConfiguration events (reduce the impact of the disorder of asynchronous tasks. Before RPC and transactions are implemented, the apiConfiguration merging phenomenon that occurs when switching profiles at high speed will not be completely solved)

4. Improved model loading requests. Users can get model list feedback in time when entering URLs, avoiding redundant interval updates

https://github.com/user-attachments/assets/d9fadecb-af64-4d24-9ffb-64cd9d84659f

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the patterns of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Reviewers

----

> [!IMPORTANT]
> Fixes input box revert and configuration loss during profile switch, improves performance and loading logic in `ClineProvider.ts`, `ApiOptions.tsx`, and `ExtensionStateContext.tsx`.
> 
>   - **Behavior**:
>     - Fix input box reverting issue by changing `onBlur` to `onInput` in `ApiOptions.tsx`.
>     - Resolve configuration loss during profile switch by ensuring `updateGlobalState` and `storeSecret` calls are wrapped in `Promise.all` in `ClineProvider.ts`.
>     - Improve profile switching performance by optimizing asynchronous operations with `Promise.all` in `ClineProvider.ts`.
>     - Enhance local model loading logic by replacing `useInterval` with `setTimeout` in `ApiOptions.tsx`.
>   - **Error Handling**:
>     - Update error messages for API configuration save and rename operations in `ClineProvider.ts`.
>   - **Misc**:
>     - Remove `softUpdate` logic from `handleInputChange` in `ExtensionStateContext.tsx` to ensure immediate synchronization.
> 
> <sup>This description was created by </sup>[Ellipsis](https://www.ellipsis.dev?ref=RooVetGit%2FRoo-Code&utm_source=github&utm_medium=referral)<sup> for 5c10e96b68f1660532706f8a1857073f0d8e6508. It will automatically update as commits are pushed.</sup>

### CODE REVIEW

**Comment by System233** [comment]
image

Why? Is this unit test correct?

**Comment by System233** [comment]
> image
> 
> Why? Is this unit test correct?

Fixed.
Removed the test "handles buildApiHandler error in updateApiConfiguration" because `upsertApiConfiguration` will no longer actively update the UI to prevent overwriting user input.

File: webview-ui/src/components/settings/ApiOptions.tsx [hunk 1]
```diff
@@ -1105,7 +1101,7 @@ const ApiOptions = ({ apiErrorMessage, modelIdErrorMessage, fromWelcomeView }: A
 						value={apiConfiguration?.lmStudioBaseUrl || ""}
 						style={{ width: "100%" }}
 						type="url"
-						onBlur={handleInputChange("lmStudioBaseUrl")}
+						onInput={handleInputChange("lmStudioBaseUrl")}
```
Comment (mrubens) [inline webview-ui/src/components/settings/ApiOptions.tsx:1104]: Does this need to change? I've been trying to get away from the onInput updates.

**Comment by mrubens** [comment]
Awesome - this looks way cleaner! Do you mind explaining which issues were fixed for you from each part of these changes? I confess that all of this code has gotten very complicated and I don't understand all of it.

**Comment by bramburn** [comment]
nice mate!

File: webview-ui/src/components/settings/ApiOptions.tsx (hunk 1 above)
Comment (System233) [reply webview-ui/src/components/settings/ApiOptions.tsx:1104]: This is to avoid useless interval calls. The model list is loaded only when the user switches the provider or changes the URL (on-demand loading to avoid UI refresh every two seconds).
Don't worry about triggering a large number of loading requests. This part has been debounced. Loading will only be triggered after the user stops typing for 250ms.
If this modification is revoked, the model list will not be updated until the input box loses focus, and the user cannot perceive whether the input is correct during typing.

**Comment by System233** [comment]
> Awesome - this looks way cleaner! Do you mind explaining which issues were fixed for you from each part of these changes? I confess that all of this code has gotten very complicated and I don't understand all of it.

The content of the revision is basically the same as the summary generated by AI, there is one error that needs to be corrected, I will set the PR as a draft first.

File: webview-ui/src/components/settings/ApiOptions.tsx (hunk 1 above)
Comment (mrubens) [reply webview-ui/src/components/settings/ApiOptions.tsx:1104]: Got it, that makes sense for loading the model list. Isn't there also something where state change messages get sent back and forth from the webview on every keystroke as well though? The intention of my change from onInput to onBlur was to avoid that, though I hear you about not getting immediate feedback to the users.

Comment (System233) [reply webview-ui/src/components/settings/ApiOptions.tsx:1104]: I have removed postStateToWebview from upsertApiConfiguration so that it only saves the configuration and does not update the UI in reverse again.
However, this breaks the function of automatically switching to a new profile when adding a profile. Next, I will split it into saveApiConfiguration to specifically provide a save function without forced UI updates.

**Comment by System233** [comment]
> Awesome - this looks way cleaner! Do you mind explaining which issues were fixed for you from each part of these changes? I confess that all of this code has gotten very complicated and I don't understand all of it.

code updated, see Description for details of the changes

**Comment by System233** [comment]
> nice mate!

Thanks! 😄

File: webview-ui/src/components/settings/ApiOptions.tsx (hunk 1 above)
Comment (mrubens) [reply webview-ui/src/components/settings/ApiOptions.tsx:1104]: Ahh I see! Should we revert my changes in https://github.com/RooVetGit/Roo-Code/pull/889 then?

Comment (System233) [reply webview-ui/src/components/settings/ApiOptions.tsx:1104]: Currently, only the fields that trigger model loading need onInput events, and other fields can keep onBlur.
Since the save process is asynchronous, in order to avoid old values ​​overwriting new values, the save frequency should be reduced.
Ideally, all input saves should use the onBlur event, and onInput is only used to update the model list. I will submit another modification later to solve potential asynchronous concurrency issues.

Comment (System233) [reply webview-ui/src/components/settings/ApiOptions.tsx]: I have changed the code but it seems that the unit test of the current main branch does not pass.

Comment (System233) [reply webview-ui/src/components/settings/ApiOptions.tsx]: BTW, #889 is fine, no need to revert it.

**Comment by System233** [comment]
After testing, the issue with editing fields in the settings panel has been resolved, but the same issue still persists during the API response process. This might be due to the rapid updates of `ExtensionStateContext` during the conversation. 

Fixing this issue would require widespread changes, so it is recommended to mark the settings as read-only during the API response process.

File: src/core/webview/ClineProvider.ts [hunk 2]
```diff
@@ -1310,6 +1310,20 @@ export class ClineProvider implements vscode.WebviewViewProvider {
...
+								await this.updateGlobalState("listApiConfigMeta", listApiConfig)
+							} catch (error) {
+								this.outputChannel.appendLine(
+									`Error save api configuration: ${JSON.stringify(error, Object.getOwnPropertyNames(error), 2)}`,
+								)
+								vscode.window.showErrorMessage("Failed to save api configuration")
+							}
+						}
+						break
 					case "upsertApiConfiguration":
```
Comment (samhvw8) [inline src/core/webview/ClineProvider.ts:1327]: @mrubens  @System233  i have an idea that remove upsertApiConfiguration and use saveApiConfiguration, 
we will have a little bit more change, on handleSubmit we will add 1 more loadApiConfiguration to that section, so we will decouple save & load api

Comment (samhvw8) [reply src/core/webview/ClineProvider.ts:1327]: @System233  @mrubens like this  https://github.com/System233/Roo-Code/pull/1  ?

**Comment by bramburn** [comment]
So my fix might still be worth working on... I started working on a local
storage save for the webview UI and adding a queue system for it.

**Comment by System233** [comment]
> So my fix might still be worth working on... I started working on a local storage save for the webview UI and adding a queue system for it.

To achieve this, the simplest solution is to cut off the connection of the settings panel to the ExtensionStateContext.
The perfect solution would be to eliminate all postStateToWebview calls and replace it with RPC/ACK.

@mrubens Could you please continue to review this PR? Thanks.

**Comment by mrubens** [comment]
> > So my fix might still be worth working on... I started working on a local storage save for the webview UI and adding a queue system for it.
> 
> To achieve this, the simplest solution is to cut off the connection of the settings panel to the ExtensionStateContext. The perfect solution would be to eliminate all postStateToWebview calls and replace it with RPC/ACK.
> 
> @mrubens Could you please continue to review this PR? Thanks.

Sorry for the delay - I’m on vacation this weekend and don’t have much time at the laptop. I can try tonight though. @samhvw8 wrote a lot of the original code so I’m curious for his thoughts as well. Thank you!

**Comment by samhvw8** [comment]
@System233  @mrubens  

i have an idea that remove upsertApiConfiguration and replace it with saveApiConfiguration, on handleSubmit in setting page we will add 1 more loadApiConfiguration to that section, so we will decouple save & load api

**Comment by System233** [comment]
Since the issue was raised, I’ve been unable to use the settings panel properly for several consecutive days. The configuration items I enter through the keyboard are often automatically deleted, and switching profiles can corrupt the correct profile, displaying a hybrid profile made up of fields from multiple profiles. This leads to issues like #1017 and #990 (which I’ve encountered firsthand), so I’m eager to fix this issue as soon as possible.

@samhvw8, your suggestion is exactly what I initially thought. In the first version of this PR(https://github.com/RooVetGit/Roo-Code/commit/5c10e96b68f1660532706f8a1857073f0d8e6508), the functionality of `upsertApiConfiguration` was identical to `saveApiConfiguration`, and I intentionally renamed `upsertApiConfiguration` to `saveApiConfiguration`. Later, to fix the issue where the new profile wasn’t automatically switched when added, I planned to handle both saving and loading operations in `handleSubmit`. However, I realized that there’s no guaranteed synchronization between `loadApiConfiguration` and `saveApiConfiguration`. Due to potential disk I/O or communication delays etc., `saveApiConfiguration` might execute after `loadApiConfiguration`, causing a profile switch to fail or resulting in a mix of old and new profiles (though, since both profiles are essentially the same, the mix still leads to the same result). Therefore, I decided to keep the original `upsertApiConfiguration` (which already encapsulates saving and UI refresh functionality in a synchronous operation) and introduce a new `saveApiConfiguration` to address this issue.

Currently, many patches related to `onBlur`/`onInput` in the project are a result of synchronization issues. I'm not sure how much you all know about data races, but synchronization is not exclusive to native languages like C/C++. Asynchronous tasks also need synchronization. Without proper synchronization mechanisms, operations must be atomic. If neither synchronization nor atomicity is ensured, there’s a risk of data corruption. Unfortunately, many parts of the Roo project haven’t addressed this, and I don't want to introduce RPC sync into the current PR, it should be a separate patch.

Finally, to resolve the issue of the settings panel rendering with old values when the state is updated, I had to revert the changes made in #889 and restore `onBlur` back to the original `onInput`.

**Comment by mrubens** [comment]
Thank you for driving this forward, and sorry I haven’t been that available while on vacation! I’m going to review this as soon as I can.

**Comment by System233** [comment]
It’s okay. At the moment, I’ve found an bug with the `Dropdown` component in `vscrui`, and I’ve already create a PR estruyf/vscrui#6. Before the patch is merged into the component library, the event handler for the `Dropdown` won’t update along with the component, which could potentially cause incorrect data. For now, I’m replacing it with the built-in `VSCodeDropdown` component to fix the issue.

**Comment by mrubens** [comment]
I just poked around a bit and it seems to work well! Nice that you were able to bring back the onInput without the typing in the boxes being laggy.

As for the vscrui - one option would be for us to use a Roo fork of it? I don't know how actively maintained it is. Let me know if you want me to create a fork within Roo, or if it's not too much trouble going back to the VS Code dropdown that's fine with me too.

File: src/core/webview/ClineProvider.ts [hunk 3]
```diff
@@ -1372,6 +1388,7 @@ export class ClineProvider implements vscode.WebviewViewProvider {
 							try {
 								const apiConfig = await this.configManager.loadConfig(message.text)
 								const listApiConfig = await this.configManager.listConfig()
+								console.log("loadApiConfiguration", message.text, apiConfig)
```
Comment (mrubens) [inline src/core/webview/ClineProvider.ts:1391]: Maybe we should cut this?

File: src/core/webview/ClineProvider.ts [hunk 4]
```diff
@@ -1647,51 +1664,53 @@ export class ClineProvider implements vscode.WebviewViewProvider {
...
-		await this.storeSecret("mistralApiKey", mistralApiKey)
-		await this.updateGlobalState("mistralCodestralUrl", mistralCodestralUrl)
-		await this.storeSecret("unboundApiKey", unboundApiKey)
-		await this.updateGlobalState("unboundModelId", unboundModelId)
-		await this.updateGlobalState("unboundModelInfo", unboundModelInfo)
-		await this.storeSecret("requestyApiKey", requestyApiKey)
-		await this.updateGlobalState("requestyModelId", requestyModelId)
-		await this.updateGlobalState("requestyModelInfo", requestyModelInfo)
-		await this.updateGlobalState("modelTemperature", modelTemperature)
+		await Promise.all([
```
Comment (mrubens) [inline src/core/webview/ClineProvider.ts:1667]: Great catch here

File: webview-ui/src/context/ExtensionStateContext.tsx [hunk 5]
```diff
@@ -190,6 +176,7 @@ export const ExtensionStateContextProvider: React.FC<{ children: React.ReactNode
 
 	const handleMessage = useCallback(
 		(event: MessageEvent) => {
+			console.log("handleMessage", event)
```
Comment (mrubens) [inline webview-ui/src/context/ExtensionStateContext.tsx:179]: Reminder to remove this before merging

**Comment by mrubens** [comment]
I'm game to try to release this tonight or tomorrow if you get it to a place where you're happy with it. Thanks again so much for digging into this 🙌

File: src/core/config/ConfigManager.ts [hunk 6]
```diff
@@ -33,29 +33,38 @@ export class ConfigManager {
 		return Math.random().toString(36).substring(2, 15)
 	}
 
+	// Synchronize readConfig/writeConfig operations to avoid data loss.
+	private _lock = Promise.resolve()
+	private lock<T>(cb: () => Promise<T>) {
+		const next = this._lock.then(cb)
+		this._lock = next.catch(() => {}) as Promise<void>
+		return next
+	}
```
Comment (samhvw8) [inline src/core/config/ConfigManager.ts:42]: this cool

**Comment by System233** [comment]
One bad news is that `VSCodeDropdown` still has its issue, which was commented on by the upstream `cline`:

```
/*
VSCodeDropdown has an open bug where dynamically rendered options don't auto select the provided value prop. You can see this for yourself by comparing it with normal select/option elements, which work as expected.
https://github.com/microsoft/vscode-webview-ui-toolkit/issues/433

In our case, when the user switches between providers, we recalculate the selectedModelId depending on the provider, the default model for that provider, and a modelId that the user may have selected. Unfortunately, the VSCodeDropdown component wouldn't select this calculated value, and would default to the first "Select a model..." option instead, which makes it seem like the model was cleared out when it wasn't.

As a workaround, we create separate instances of the dropdown for each provider, and then conditionally render the one that matches the current provider.
*/
```

However, there’s good news too—`vscrui` has merged the patch, and we can now use the fixed version.

**Review by mrubens — APPROVED** [review]
🚀

**Comment by mrubens** [comment]
Awesome, feel free to merge whenever you feel good about it!

**Comment by hannesrudolph** [comment]
@System233 can you please shoot me a message on discord? hrudolph is my user id.

**Comment by System233** [comment]
> Awesome, feel free to merge whenever you feel good about it!

Thanks. I’m working on resolving the issue where unsaved configurations in the settings panel are lost once the API response is completed, which behaves the same as the upstream `cline` behavior. Apart from that, no other issues have been found.

> @System233 can you please shoot me a message on discord? hrudolph is my user id.

Sorry about that, I don't have a Discord account.

**Comment by System233** [comment]
Since `postStateToWebview/apiConfiguration` is used extensively, modifying the code would have a significant impact, and there isn’t an immediate good solution to this problem. Considering that the impact of this issue is relatively small, we can merge the PR for now and address this issue separately in the future.

> Awesome, feel free to merge whenever you feel good about it!

@mrubens 
I don’t have merge permissions, so the maintainers can merge the PR anytime after you’ve reviewed it. Thank you. 👌

**Comment by mrubens** [comment]
Someone in discord noticed that there are still issues with renaming profiles (check out around 2:00 into this video). Any ideas what could be going on there? Thank you!

https://github.com/user-attachments/assets/c184e342-4612-4a03-b10e-17ffaf9e7a75

**Comment by System233** [comment]
> Someone in discord noticed that there are still issues with renaming profiles (check out around 2:00 into this video). Any ideas what could be going on there? Thank you!
> 
>  Code_9DwSQCj3cN.mp4

I’ve checked the issue, and it’s caused by the settings not being saved. Currently, the configuration is only saved after clicking the Done button or switching profiles, but renaming doesn’t trigger the save functionality.

There’s still a synchronization issue here. I can solve this by wrapping the rename event handler into a synchronous operation that saves and loads the configuration. 
Alternatively, I’d like to implement something similar to the versioning mechanism in SQL, where only the latest state is saved. This way, configurations can be saved immediately in the input event, while also addressing potential event ordering issues.

**Comment by System233** [comment]
patch almost ready, create a PR to fix the issue later

**Comment by System233** [comment]
> I’m working on resolving the issue where unsaved configurations in the settings panel are lost once the API response is completed, which behaves the same as the upstream behavior `cline`


> Someone in discord noticed that there are still issues with renaming profiles (check out around 2:00 into this video). Any ideas what could be going on there? Thank you!
> 
>  Code_9DwSQCj3cN.mp4

All of the above fixed in #1051
