### PR TITLE
Fix provider 400s: strip reasoning_details from messages, $ref from tool schemas

### LINKED ISSUE #11429: Anthropic 400: reasoning_details rejected as extra input
## Bug description

When sending messages to Anthropic, the API returns a 400 error rejecting `reasoning_details` as an extra field:

```
Date/time: 2026-01-15T20:42:36.457Z
Extension version: 3.40.1
Provider: anthropic
Model: claude-opus-4-5-20251101

400 {"type":"error","error":{"type":"invalid_request_error","message":"messages.1.reasoning_details: Extra inputs are not permitted"},"request_id":"req_011CX9p8grvbBemMRVbtW3Md"}
```

## Likely root cause

`anthropic.ts` and `openrouter.ts` cast `messages as ModelMessage[]` without stripping extra fields. Messages loaded from persisted JSON storage carry `reasoning_details` and `reasoning_content` from previous reasoning model interactions. The TypeScript cast is a no-op at runtime, so these extra fields survive into the outbound API request. Anthropic rejects the unknown fields.

## Steps to reproduce

1. Have a conversation history containing messages with `reasoning_details` fields (from prior reasoning model interactions)
2. Continue the conversation using Anthropic as provider
3. Observe 400 error: "messages.1.reasoning_details: Extra inputs are not permitted"

## Expected behavior

Extra legacy fields should be stripped from messages before sending to provider APIs.

### LINKED ISSUE #11430: OpenRouter/Gemini 400: unresolvable $ref in tool schema
## Bug description

When using OpenRouter with a Gemini model, the API returns a 400 error referencing an unresolvable `$ref` in the tool schema:

```
Date/time: 2026-01-15T20:37:33.484Z
Extension version: 3.40.1
Provider: openrouter
Model: google/gemini-3-pro-preview

400 INVALID_ARGUMENT: "The referenced name #/components/schemas/PlanningLogResponse in function_response.response does not match to a display_name in the function_response.parts."
```

## Likely root cause

`normalizeToolSchema()` in `json-schema.ts` allows `$ref` to pass through via `...rest` in the Zod transform destructuring. MCP tool schemas containing `$ref` references (e.g. `#/components/schemas/PlanningLogResponse`) are sent to OpenRouter, which forwards them to Gemini. Gemini cannot resolve the references and rejects the request.

## Steps to reproduce

1. Use an MCP tool whose schema contains `$ref` references
2. Send a request to OpenRouter targeting a Gemini model (e.g. `google/gemini-3-pro-preview`)
3. Observe 400 error: `INVALID_ARGUMENT` referencing an unresolvable `$ref`

## Expected behavior

`$ref` references should be stripped from tool schemas during normalization, since LLM API providers cannot resolve JSON Schema references.

### PR DESCRIPTION
**Pull request by 0xMink**
Closes #11429
Closes #11430

## Summary

- Strip `reasoning_details` and `reasoning_content` from messages before sending to provider APIs. These legacy fields survive JSON deserialization and the no-op TypeScript cast (`messages as ModelMessage[]`), causing providers to reject the request with "Extra inputs are not permitted."
- Strip `$ref` from tool schemas during normalization in `json-schema.ts`. MCP tool schemas containing unresolvable `$ref` references (e.g. `#/components/schemas/...`) cause providers to reject the request with `INVALID_ARGUMENT`.
- Apply the message sanitization to both the direct provider handler and the OpenRouter handler, which had the identical no-op cast bug.

## Test plan

- **Existing:** 28 json-schema normalization tests, 26 provider tests -- all passing
- **New:** 1 test asserting `reasoning_details` and `reasoning_content` are stripped from messages before the `streamText` call
- **New:** 5 tests asserting `$ref` is stripped at all nesting depths (top-level, nested properties, array items, anyOf variants, $ref-only schema)
- Verified via `cmd.exe /c 'cd /d ...\src && npx vitest run utils/__tests__/json-schema.spec.ts api/providers/__tests__/anthropic.spec.ts'` -- 60/60 passing

### CODE REVIEW

**Comment by ghost** [comment]
> **Rooviewer**  Clock &nbsp;&nbsp;[See task](https://app.roocode.com/cloud-jobs/H5L3y7Zx?utm_source=github-comment&utm_medium=link&utm_campaign=github.pr.review.sync)

All previously flagged issues have been resolved. No new issues found.

- [x] **anthropic.ts**: `.map()` creates new message objects but `applyCacheControlToAiSdkMessages` still mutates the original `messages` array -- prompt caching silently breaks because `streamText` receives the unmutated copies

> <details>
> <summary>Previous reviews</summary>
> 
> - 130c7b4: [Review #1](https://app.roocode.com/cloud-jobs/ZrGitFqt?utm_source=previous-reviews&utm_medium=link&utm_campaign=github.pr.review)
> - f06234c: [Review #2](https://app.roocode.com/cloud-jobs/4j1nxPZr?utm_source=previous-reviews&utm_medium=link&utm_campaign=github.pr.review)
> - 7375a59: [Review #3](https://app.roocode.com/cloud-jobs/gIqWeI87?utm_source=previous-reviews&utm_medium=link&utm_campaign=github.pr.review)
> - e37855b: [Review #4](https://app.roocode.com/cloud-jobs/l3BKwLoq?utm_source=previous-reviews&utm_medium=link&utm_campaign=github.pr.review)
> </details>
<sub>Mention @roomote in a comment to request specific changes to this pull request or [fix all unresolved issues](https://app.roocode.com/fix-issues?repo=RooCodeInc/Roo-Code&prNumber=11431&commentId=3888517286).</sub>

File: src/api/providers/anthropic.ts [hunk 1]
```diff
@@ -76,8 +76,12 @@ export class AnthropicHandler extends BaseProvider implements SingleCompletionHa
...
 		const modelConfig = this.getModel()
 
-		// Convert messages to AI SDK format
-		const aiSdkMessages = messages as ModelMessage[]
+		// Convert messages to AI SDK format, stripping extra fields from legacy
+		// ApiMessage objects that survive JSON deserialization (e.g. reasoning_details
+		// causes Anthropic 400: "Extra inputs are not permitted").
+		const aiSdkMessages = messages.map(
+			({ reasoning_details, reasoning_content, ...rest }: any) => rest,
+		) as ModelMessage[]
```
Comment (ghost) [inline src/api/providers/anthropic.ts]: This `.map()` creates a new array of new objects, but `applyCacheControlToAiSdkMessages` on line 129 still receives `messages as ModelMessage[]` (the original array). Since `streamText` on line 140 uses `aiSdkMessages` (the mapped copy), the `providerOptions` set by `applyCacheControlToAiSdkMessages` never reach the objects actually sent to the API. Before this change the cast was a no-op so both variables referenced the same objects and mutations propagated. Now prompt caching is silently broken. Line 129 should pass `aiSdkMessages` instead of `messages as ModelMessage[]`.

<sub>[Fix it with Roo Code](https://app.roocode.com/fix-issue/?repo=RooCodeInc/Roo-Code&prNumber=11431&fixId=2bafd0b81c) or mention @roomote and request a fix.</sub>

**Comment by 0xMink** [comment]
Good catch @roomote. Fixed in 7375a59 -- `applyCacheControlToAiSdkMessages` now receives `aiSdkMessages` (the mapped copy) instead of the original array.
