### PR TITLE
Auto approve follow up questions

### LINKED ISSUE #1887: LLM often feels forced to ask a question via "Roo has a question"
### Which version of the app are you using?

v3.10.1

### Which API Provider are you using?

OpenRouter

### Which Model are you using?

Claude 3.5 Sonnet, different Gemini models

### What happened?

The new feature for the LLM to ask a question is contra productive to the workflow.
Claude and Gemini feel compelled to ask questions all the time, which often results in echoing back my own questions instead of answering them. The new "buttons" in the latest version are as well more of a token eater than helpful to the workflow and directly related to "Roo has a question". The generated buttons, when clicked, just force another API call without the ability to add more context. They feel more like a feature for "Vibe Coding", where token count doesn't matter as much and a button like "Let's consider other options entirely" might result in some interesting outcome. They often do not add value as they are now and only add to the token count.

### Steps to reproduce

1.
2.
3.

### Relevant API REQUEST output

```shell

```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by liwilliam2021**
Fixes #1887

Added auto approve for questions-- adjustable setting for how long Roo will wait when asking a question before proceeding with the most likely answer

[Loom Video of Changes](https://www.loom.com/share/8fedb8a903c14f18bfb4e7e3ead207d4)

### CODE REVIEW

File: webview-ui/src/components/chat/ChatView.tsx [hunk 1]
```diff
@@ -1270,19 +1277,35 @@ const ChatViewComponent: React.ForwardRefRenderFunction<ChatViewRef, ChatViewPro
...
+						handleSuggestionClickInRow(suggestionText)
+						return
+					}
+				} else if (lastMessage.ask === "tool" && isWriteToolAction(lastMessage)) {
 					await new Promise<void>((resolve) => {
 						autoApproveTimeoutRef.current = setTimeout(resolve, writeDelayMs)
 					})
 				}
 
-				if (autoApproveTimeoutRef.current === null || autoApproveTimeoutRef.current) {
```
Comment (liwilliam2021) [inline webview-ui/src/components/chat/ChatView.tsx:1279]: Deleted because I think this always evaluates to true?

Comment (liwilliam2021) [reply webview-ui/src/components/chat/ChatView.tsx:1279]: It seems like this was an attempt to get the request to cancel if the timeout is canceled, but I think this already happens by default

Comment (liwilliam2021) [reply webview-ui/src/components/chat/ChatView.tsx:1279]: Dan says safe to remove!

File: webview-ui/src/components/chat/ChatView.tsx [hunk 2]
```diff
@@ -1270,19 +1277,35 @@ const ChatViewComponent: React.ForwardRefRenderFunction<ChatViewRef, ChatViewPro
 
 		const autoApprove = async () => {
 			if (lastMessage?.ask && isAutoApproved(lastMessage)) {
-				if (lastMessage.ask === "tool" && isWriteToolAction(lastMessage)) {
+				// Special handling for follow-up questions
+				if (lastMessage.ask === "followup") {
+					const followUpData = JSON.parse(lastMessage.text || "{}")
```
Comment (daniel-lxs) [inline webview-ui/src/components/chat/ChatView.tsx]: The JSON.parse() here could throw an error if lastMessage.text contains invalid JSON. Could we wrap this in a try-catch block to handle potential parsing errors gracefully?

```typescript
let followUpData;
try {
  followUpData = JSON.parse(lastMessage.text || "{}")
} catch (error) {
  console.error('Failed to parse follow-up data:', error);
  return;
}
```

File: webview-ui/src/components/chat/FollowUpSuggest.tsx [hunk 3]
```diff
@@ -18,7 +19,47 @@ interface FollowUpSuggestProps {
...
+					if (prevCountdown === null || prevCountdown <= 1) {
+						clearInterval(intervalId)
+						return null
+					}
+					return prevCountdown - 1
+				})
+			}, 1000)
+
+			// Clean up interval on unmount
+			return () => clearInterval(intervalId)
```
Comment (daniel-lxs) [inline webview-ui/src/components/chat/FollowUpSuggest.tsx]: I notice there's a potential race condition here. If the component unmounts while the countdown is active, the interval cleanup happens, but what if the auto-approval in ChatView.tsx is still waiting? Could we consider using a shared cancellation mechanism or ensuring the ChatView's timeout is also cleared when this component unmounts?

File: webview-ui/src/components/chat/ChatView.tsx (hunk 2 above)
Comment (daniel-lxs) [inline webview-ui/src/components/chat/ChatView.tsx]: Would it be beneficial to define a TypeScript interface for the followUpData structure? This would provide better type safety and make the expected structure clearer:

```typescript
interface FollowUpData {
  suggest?: Array<string | { answer: string; mode?: string }>;
}
```

File: webview-ui/src/components/chat/FollowUpSuggest.tsx [hunk 4]
```diff
@@ -32,6 +73,11 @@ export const FollowUpSuggest = ({ suggestions = [], onSuggestionClick, ts = 1 }:
 				})
 			}
 
+			// Mark a suggestion as selected if it's not a shift-click (which just copies to input)
+			if (!event.shiftKey) {
+				setSuggestionSelected(true)
```
Comment (daniel-lxs) [inline webview-ui/src/components/chat/FollowUpSuggest.tsx:72]: I see that `setSuggestionSelected(true)` is called when a suggestion is clicked (non-shift click), but I'm wondering if this properly cancels the auto-approval timeout in ChatView? The countdown stops displaying here, but the ChatView might still be waiting to auto-approve. Should we ensure the parent component is notified to cancel its timeout?

File: webview-ui/src/components/chat/FollowUpSuggest.tsx [hunk 5]
```diff
@@ -18,7 +19,47 @@ interface FollowUpSuggestProps {
...
+
+	// Start countdown timer when auto-approval is enabled for follow-up questions
+	useEffect(() => {
+		// Only start countdown if auto-approval is enabled for follow-up questions and no suggestion has been selected
+		if (autoApprovalEnabled && alwaysAllowFollowupQuestions && suggestions.length > 0 && !suggestionSelected) {
+			// Start with the configured timeout in seconds
+			const timeoutMs =
+				typeof followupAutoApproveTimeoutMs === "number" && !isNaN(followupAutoApproveTimeoutMs)
+					? followupAutoApproveTimeoutMs
+					: 10000
```
Comment (daniel-lxs) [inline webview-ui/src/components/chat/FollowUpSuggest.tsx]: Could we extract these magic numbers as constants? This would make them easier to maintain and understand:

```typescript
const DEFAULT_FOLLOWUP_TIMEOUT_MS = 10000;
const COUNTDOWN_INTERVAL_MS = 1000;
```

**Review by daniel-lxs — COMMENTED** [review]
I took a look at your PR, it looks good. I left a couple of suggestions that might be worth considering.

Let me know what you think.

File: webview-ui/src/components/chat/ChatView.tsx [hunk 6]
```diff
@@ -1270,19 +1277,35 @@ const ChatViewComponent: React.ForwardRefRenderFunction<ChatViewRef, ChatViewPro
...
+							autoApproveTimeoutRef.current = setTimeout(resolve, followupAutoApproveTimeoutMs)
+						})
+
+						// Get the first suggestion
+						const firstSuggestion = followUpData.suggest[0]
+						const suggestionText =
+							typeof firstSuggestion === "string" ? firstSuggestion : firstSuggestion.answer
+
+						// Handle the suggestion click
+						handleSuggestionClickInRow(suggestionText)
```
Comment (mrubens) [inline webview-ui/src/components/chat/ChatView.tsx]: I think you should just pass in the whole suggestion, in case it contains a mode too.
```suggestion
						// Handle the suggestion click
						handleSuggestionClickInRow(followUpData.suggest[0])
```

File: webview-ui/src/components/chat/FollowUpSuggest.tsx (hunk 5 above)
Comment (mrubens) [reply webview-ui/src/components/chat/FollowUpSuggest.tsx]: Also, I think 10 seconds is too short as a default. Was thinking that something like 60 seconds is probably more appropriate.

**Review by daniel-lxs — APPROVED** [review]
LGTM

File: webview-ui/src/components/chat/FollowUpSuggest.tsx [hunk 7]
```diff
@@ -44,23 +89,29 @@ export const FollowUpSuggest = ({ suggestions = [], onSuggestionClick, ts = 1 }:
...
 							onClick={(event) => handleSuggestionClick(suggestion, event)}
-							aria-label={suggestionText}>
-							{suggestionText}
+							aria-label={suggestion.answer}>
+							{suggestion.answer}
+							{isFirstSuggestion && countdown !== null && !suggestionSelected && (
+								<span
+									className="ml-2 px-1.5 py-0.5 text-xs rounded-full bg-vscode-badge-background text-vscode-badge-foreground"
+									title={t("chat:followUpSuggest.autoSelectCountdown", { count: countdown })}>
+									{countdown}s
```
Comment (mrubens) [inline webview-ui/src/components/chat/FollowUpSuggest.tsx]: Probably should internationalize this
