### PR TITLE
Fix dynamic provider model validation to prevent cross-contamination

### LINKED ISSUE #9047: [BUG]
### Problem (one or two sentences)

Error Stack:
TypeError: Cannot read properties of undefined (reading 'claude-3-7-sonnet-20250219')
    at id (../../../../webview-ui/src/components/ui/hooks/useSelectedModel.ts:180:37)
    at getSelectedModel (../../../../webview-ui/src/components/ui/hooks/useSelectedModel.ts:101:5)
    at transform (../../../../webview-ui/src/components/settings/ApiOptions.tsx:191:5)
    at Nh (../../../../node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom.production.min.js:160:136)
    at gj (../../../../node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom.production.min.js:196:257)
    at bj (../../../../node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom.production.min.js:194:203)
    at Fk (../../../../node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom.production.min.js:296:99)
    at tj (../../../../node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom.production.min.js:279:388)
    at tj (../../../../node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom.production.min.js:279:319)
    at tj (../../../../node_modules/.pnpm/react-dom@18.3.1_react@18.3.1/node_modules/react-dom/cjs/react-dom.production.min.js:279:179)
Component Stack:

at tdn (../../../../webview-ui/src/components/settings/ApiOptions.tsx:132:1)
    at div
at _a (../../../../webview-ui/src/components/settings/Section.tsx:7:26)
    at div
    at div
    at https://vscode-remote+dev-002dcontainer-002b7b22686f737450617468223a222f55736572732f736177616e2e737562612f446f63756d656e74732f69746c2f696e746567726174696f6e2d7472616e73666f726d6174696f6e2d6c61796572222c226c6f63616c446f636b6572223a66616c73652c22636f6e66696746696c65223a7b22246d6964223a312c22667350617468223a222f55736572732f736177616e2e737562612f446f63756d656e74732f69746c2f696e746567726174696f6e2d7472616e73666f726d6174696f6e2d6c617965722f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2265787465726e616c223a2266696c653a2f2f2f55736572732f736177616e2e737562612f446f63756d656e74732f69746c2f696e746567726174696f6e2d7472616e73666f726d6174696f6e2d6c617965722f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2270617468223a222f55736572732f736177616e2e737562612f446f63756d656e74732f69746c2f696e746567726174696f6e2d7472616e73666f726d6174696f6e2d6c617965722f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a2266696c65227d7d.vscode-resource.vscode-cdn.net/home/vscode/.vscode-server/extensions/rooveterinaryinc.roo-cline-3.30.1/webview-ui/build/assets/index.js:2617:8438
    at div
    at div
at wm (../../../../webview-ui/src/components/common/Tab.tsx:8:22)
    at https://vscode-remote+dev-002dcontainer-002b7b22686f737450617468223a222f55736572732f736177616e2e737562612f446f63756d656e74732f69746c2f696e746567726174696f6e2d7472616e73666f726d6174696f6e2d6c61796572222c226c6f63616c446f636b6572223a66616c73652c22636f6e66696746696c65223a7b22246d6964223a312c22667350617468223a222f55736572732f736177616e2e737562612f446f63756d656e74732f69746c2f696e746567726174696f6e2d7472616e73666f726d6174696f6e2d6c617965722f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2265787465726e616c223a2266696c653a2f2f2f55736572732f736177616e2e737562612f446f63756d656e74732f69746c2f696e746567726174696f6e2d7472616e73666f726d6174696f6e2d6c617965722f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c2270617468223a222f55736572732f736177616e2e737562612f446f63756d656e74732f69746c2f696e746567726174696f6e2d7472616e73666f726d6174696f6e2d6c617965722f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a2266696c65227d7d.vscode-resource.vscode-cdn.net/home/vscode/.vscode-server/extensions/rooveterinaryinc.roo-cline-3.30.1/webview-ui/build/assets/index.js:3464:12625
at lpn (../../../../webview-ui/src/App.tsx:82:5)
at d (../../../../node_modules/.pnpm/@radix-ui+react-context@1.1.2_@types+react@18.3.23_react@18.3.1/node_modules/@radix-ui/react-context/dist/index.mjs:27:14)
at Tbt (../../../../node_modules/.pnpm/@radix-ui+react-tooltip@1.2.6_@types+react-dom@18.3.7_@types+react@18.3.23__@types+reac_99504aa956c623e0884a4e3cb215669a/node_modules/@radix-ui/react-tooltip/dist/index.mjs:29:4)
at i$ (../../../../webview-ui/src/components/ui/tooltip.tsx:8:27)
at F_t (../../../../node_modules/.pnpm/@tanstack+react-query@5.76.1_react@18.3.1/node_modules/@tanstack/react-query/build/modern/QueryClientProvider.js:20:2)
at Ojt (../../../../webview-ui/src/i18n/TranslationContext.tsx:16:73)
at Njt (../../../../webview-ui/src/context/ExtensionStateContext.tsx:192:89)
at epn (../../../../webview-ui/src/components/ErrorBoundary.tsx:18:2)
at i (../../../../node_modules/.pnpm/react-i18next@15.5.1_i18next@25.2.1_typescript@5.8.3__react-dom@18.3.1_react@18.3.1__react@18.3.1_typescript@5.8.3/node_modules/react-i18next/dist/es/withTranslation.js:6:4)
    at dpn

### Context (who is affected and when)

Tried switching the provider after selecting the model

### Reproduction steps

Tried switching the provider after selecting the model

### Expected result

Tried switching the provider after selecting the model

### Actual result

Tried switching the provider after selecting the model

### Variations tried (optional)

_No response_

### App Version

v3.30.1

### API Provider (optional)

None

### Model Used (optional)

_No response_

### Roo Code Task Links (optional)

_No response_

### Relevant logs or errors (optional)

```shell

```

### PR DESCRIPTION
**Pull request by daniel-lxs**
## Problem

When switching between dynamic providers (like OpenRouter to Chutes), the extension would sometimes default to Claude Sonnet 4 instead of the provider's default model. This happened because configured model IDs from the previous provider were being used with the new provider, even when that model doesn't exist in the new provider's model list.

Additionally, when users switch providers after selecting a model, the router models for the new provider may not be loaded yet, causing a TypeError when the code tries to access properties on undefined objects (fixes #9047).

## Root Cause

The issue was cross-contamination between providers. For example:
1. User selects OpenRouter with model `anthropic/claude-sonnet-4.5`
2. User switches to Chutes 
3. `apiConfiguration.apiModelId` still contains `anthropic/claude-sonnet-4.5`
4. Chutes doesn't have this model, so it falls back to default
5. But the fallback was inconsistently applied

### 1. Created reusable validation helper
Added `getValidatedModelId()` function that ensures the configured model ID exists in the current provider's available models before using it.

### 2. Applied to ALL dynamic providers
Updated all 10 dynamic providers that use `routerModels`:
- OpenRouter
- Requesty  
- Glama
- Unbound
- LiteLLM
- Chutes (the main culprit)
- DeepInfra
- IO Intelligence
- Roo
- Vercel AI Gateway

### 3. Centralized default model logic
Created `getProviderDefaultModelId()` function to centralize provider default model logic and reduce import bloat.

### 4. Added optional chaining for TypeError prevention
Added optional chaining (`?.`) to all router model accesses to safely handle cases where router models are undefined during provider transitions.

## Benefits
- **Consistent behavior**: All dynamic providers handle model validation identically
- **DRY principle**: Single validation logic instead of 10+ repeated implementations  
- **Bug prevention**: Eliminates cross-contamination when switching providers
- **Maintainability**: Future changes only need to be made in one place
- **Type safety**: All changes are properly typed
- **Enhanced robustness**: Prevents TypeError during provider transitions

## Testing
- TypeScript compilation passes
- ESLint passes with no warnings
- All pre-commit hooks pass

Fixes #9047 and supersedes #9049

### CODE REVIEW

**Comment by ghost** [comment]
> **Rooviewer**  Clock &nbsp;&nbsp;[See task on Roo Cloud](https://app.roocode.com/cloud-jobs/stbsjA0d?utm_source=cloud-job-url&utm_medium=link&utm_campaign=github.pr.review.sync)

All issues have been resolved.

- [x] Fix `vercel-ai-gateway` validation to pass raw config value to `getValidatedModelId()` for consistency with other dynamic providers

> <details>
> <summary>Previous reviews</summary>
> 
> - c693f1c: [Review #1](https://app.roocode.com/cloud-jobs/YquaPOKB?utm_source=cloud-job-url&utm_medium=link&utm_campaign=previous-reviews)
> - 9da1589: [Review #2](https://app.roocode.com/cloud-jobs/Uw6KYszT?utm_source=cloud-job-url&utm_medium=link&utm_campaign=previous-reviews)
> - c1281a5: [Review #3](https://app.roocode.com/cloud-jobs/Qa1TdAnf?utm_source=cloud-job-url&utm_medium=link&utm_campaign=previous-reviews)
> - a72aae3: [Review #4](https://app.roocode.com/cloud-jobs/stbsjA0d?utm_source=cloud-job-url&utm_medium=link&utm_campaign=previous-reviews)
> </details>


<sub>Mention @roomote to ask your PR Fixer agent to address the feedback.</sub>

File: webview-ui/src/components/ui/hooks/useSelectedModel.ts [hunk 1]
```diff
@@ -321,49 +312,56 @@ function getSelectedModel({
...
 		case "qwen-code": {
-			const id = apiConfiguration.apiModelId ?? qwenCodeDefaultModelId
+			const id = apiConfiguration.apiModelId ?? defaultModelId
 			const info = qwenCodeModels[id as keyof typeof qwenCodeModels]
 			return { id, info }
 		}
 		case "vercel-ai-gateway": {
-			const id = apiConfiguration.vercelAiGatewayModelId ?? vercelAiGatewayDefaultModelId
+			const id = getValidatedModelId(
+				apiConfiguration.vercelAiGatewayModelId ?? defaultModelId,
```
Comment (ghost) [inline webview-ui/src/components/ui/hooks/useSelectedModel.ts]: The first parameter to `getValidatedModelId()` should be the raw `apiConfiguration.vercelAiGatewayModelId` without the `?? defaultModelId` fallback. Currently, if `vercelAiGatewayModelId` is undefined, it pre-emptively falls back to `defaultModelId` before validation, which bypasses the helper's validation logic. This is inconsistent with all other dynamic providers (openrouter, requesty, glama, etc.) which pass the raw config value and let the helper handle undefined cases.

<sub>[Fix it with Roo Code](https://app.roocode.com/fix-issue/?repo=RooCodeInc/Roo-Code&prNumber=9054&fixId=b1f111e265) or mention @roomote and request a fix.</sub>

Comment (daniel-lxs) [reply webview-ui/src/components/ui/hooks/useSelectedModel.ts]: @roomote Fix this issue

**Review by mrubens — APPROVED** [review]
