### PR TITLE
fix: prevent model cache from persisting empty API responses

### LINKED ISSUE #9597: [BUG] Starting from version v3.33.2, the model ID that actually exists cannot be found in the openrouter provider, and this bug still exists in the latest version v3.34.4.
### Problem (one or two sentences)

Starting from version v3.33.2, the model ID that actually exists cannot be found in the openrouter provider, and this bug still exists in the latest version v3.34.4.
Currently, I have identified that this bug occurs in the GPT-5.1 series models, Gemini-3 model, and Grok-4.1-Fast model. It is not yet known whether other models also have the same bug.
An interesting phenomenon is that in the first few minutes after you just open Roo Code, this bug will not appear, and you can normally configure the models in OpenRouter (such as the GPT-5.1 series). However, after some time, when you open the model configuration page of Roo Code again, it will show that the GPT-5.1 series models do not exist, and the models will be automatically replaced with Claude Sonnet 4.5.

### Context (who is affected and when)

In all versions subsequent to v3.33.1, this bug will occur when you configure some models from OpenRouter. The "some models" here refer to the gpt-5.1 series, gemini-3, and grok-4.1-fast.
An interesting phenomenon is that in the first few minutes after you just open Roo Code, this bug will not appear, and you can normally configure the models in OpenRouter (such as the GPT-5.1 series). However, after some time, when you open the model configuration page of Roo Code again, it will show that the GPT-5.1 series models do not exist, and the models will be automatically replaced with Claude Sonnet 4.5.

### Reproduction steps

1. Open the settings interface of Roo Code;
2. Create a new configuration, select the "openrouter" provider, and set the model to "gpt-5.1" (the configuration can be successfully completed at this point);
3. Wait for a period of time;
4. Reopen the newly added model configuration created just now, and you will find that it shows "gpt-5.1 does not exist", and the model has been automatically switched to "Claude sonnet 4.5".

### Expected result

I expect to configure these models correctly.

### Actual result

The model configuration page indicates that the model does not exist in OpenRouter.

### Variations tried (optional)

_No response_

### App Version

afer v3.33.1

### API Provider (optional)

OpenRouter

### Model Used (optional)

gpt-5.1 series, gemini-3, and grok-4.1-fast

### Roo Code Task Links (optional)

_No response_

### Relevant logs or errors (optional)

```shell

```

### PR DESCRIPTION
**Pull request by daniel-lxs**
## Summary
Fixes #9597

This PR fixes a race condition in the model cache that caused "model ID not found" errors when API returned empty responses.

## Root Cause
When the OpenRouter API (or other providers) failed silently and returned `{}` instead of throwing an error, the empty response was being cached to both memory and disk. This overwrote valid cached data, causing subsequent model lookups to fail with "model not found" and fall back to defaults.

### 1. Empty response protection
- **`getModels()`**: Only cache non-empty API responses (>0 models)
- **`refreshModels()`**: Return existing cache when API returns empty response

### 2. In-flight request deduplication
Added `inFlightRefresh` Map to track ongoing refresh requests. When multiple calls to `refreshModels()` happen concurrently for the same provider, they now share the same promise instead of racing against each other.

### 3. Telemetry
Added new `MODEL_CACHE_EMPTY_RESPONSE` telemetry event to track when API returns empty responses, which helps identify problematic API behavior in production.

## Testing
- Added 8 new test cases covering empty response handling
- All 99 tests in the fetchers test suite pass
- All 21 tests in `modelCache.spec.ts` pass

## Files Changed
- `packages/types/src/telemetry.ts` - Added telemetry event
- `src/api/providers/fetchers/modelCache.ts` - Core fix
- `src/api/providers/fetchers/__tests__/modelCache.spec.ts` - Tests

----

> [!IMPORTANT]
> Fixes caching of empty API responses in `modelCache.ts` and adds telemetry for tracking, with concurrency improvements and new tests.
> 
>   - **Behavior**:
>     - `getModels()`: Only caches non-empty API responses.
>     - `refreshModels()`: Returns existing cache if API response is empty.
>   - **Concurrency**:
>     - Introduces `inFlightRefresh` Map to deduplicate concurrent `refreshModels()` calls.
>   - **Telemetry**:
>     - Adds `MODEL_CACHE_EMPTY_RESPONSE` event in `telemetry.ts` to track empty API responses.
>   - **Testing**:
>     - Adds 8 test cases for empty response handling in `modelCache.spec.ts`.
>   - **Files Changed**:
>     - `telemetry.ts`: Adds telemetry event.
>     - `modelCache.ts`: Implements core fix and concurrency handling.
>     - `modelCache.spec.ts`: Adds tests.
> 
> <sup>This description was created by </sup>[Ellipsis](https://www.ellipsis.dev?ref=RooCodeInc%2FRoo-Code&utm_source=github&utm_medium=referral)<sup> for c02fe6be43824a202e218db161fb8b4f25511025. You can [customize](https://app.ellipsis.dev/RooCodeInc/settings/summaries) this summary. It will automatically update as commits are pushed.</sup>

### CODE REVIEW

**Comment by ghost** [comment]
> **Rooviewer**  Clock &nbsp;&nbsp;[See task on Roo Cloud](https://app.roocode.com/cloud-jobs/fCP5sFuG?utm_source=github-comment&utm_medium=link&utm_campaign=github.pr.review.sync)

All issues resolved. The error logging has been successfully added to the refreshModels() catch block.

- [x] Add error logging in refreshModels() catch block to aid debugging when API failures occur

> <details>
> <summary>Previous reviews</summary>
> 
> - c42c03a: [Review #1](https://app.roocode.com/cloud-jobs/zHIbrBP7?utm_source=cloud-job-url&utm_medium=link&utm_campaign=previous-reviews)
> </details>
<sub>Mention @roomote in a comment to request specific changes to this pull request or [fix all unresolved issues](https://app.roocode.com/fix-issues?repo=RooCodeInc/Roo-Code&prNumber=9623&commentId=3582835174).</sub>

File: src/api/providers/fetchers/modelCache.ts [hunk 1]
```diff
@@ -164,31 +174,70 @@ export const getModels = async (options: GetModelsOptions): Promise<ModelRecord>
...
+			// Update memory cache first
+			memoryCache.set(provider, models)
+
+			// Atomically write to disk (safeWriteJson handles atomic writes)
+			await writeModels(provider, models).catch((err) =>
+				console.error(`[refreshModels] Error writing ${provider} models to disk:`, err),
+			)
+
+			return models
+		} catch {
```
Comment (ghost) [inline src/api/providers/fetchers/modelCache.ts]: The catch block silently swallows all errors without logging, making it difficult to diagnose API failures in production. While graceful degradation is appropriate, the original error should be logged for debugging purposes (similar to line 224 which logs writeModels failures).

<sub>[Fix it with Roo Code](https://app.roocode.com/fix-issue/?repo=RooCodeInc/Roo-Code&prNumber=9623&fixId=d9ce825e87) or mention @roomote and request a fix.</sub>

**Review by mrubens — APPROVED** [review]
