### PR TITLE
Fix overdependence on start/end lines in diff strategy

### LINKED ISSUE #2556: Incorrect applying of apply_diff
### App Version

3.11.14

### API Provider

LM Studio

### Model Used

athene-v2-chat@iq4_xs

### Actual vs. Expected Behavior

The diff produced looks good, but applied wrongly by Roo:
Image

The text version:
Original file:
```
7 | .chess-board-container {
8 |     display: flex;
9 |     gap: 1rem;
10 |     align-items: center;
11 | }
12 | 
13 | .overlay {
14 |     position: absolute;
15 |     top: 0;
16 |     left: 0;
17 |     width: 100%;
18 |     height: 100%;
19 |     background-color: rgba(0, 0, 0, 0.5);
20 |     z-index: 999; /* Ensure it's above the board but below the promotion dialog */
21 | }
```

The diff produced:
```
<<<<<<< SEARCH
:start_line:12
:end_line:13
-------
.overlay {
=======

.piece {
    will-change: transform;
}

.overlay {
>>>>>>> REPLACE
```

The final result:
```
10 |     align-items: center;
11 | }
12 | .piece {
13 |     will-change: transform;
14 | }
15 | 
16 | .overlay {
17 | .overlay {
```

======
Another attempt:
Image

The diff:
```
<<<<<<< SEARCH
:start_line:11
:end_line:13
-------
}
 

.overlay {
=======

}
.piece {
    will-change: transform;
}

.overlay {
>>>>>>> REPLACE
```

In the final result line with `14 |     position: absolute;` was deleted.

### Detailed Steps to Reproduce

I am working on custom prompt for apply_diff to add context lines for better match the content, so idk if the model will produce same diff content with standard prompt, but with standard prompt I also had similar issues with applying correct diffs.

Probably unit-test will help to debug, assume original content (with correct line numbers) is:
```
.game-container {
    display: flex;
    flex-direction: column;
    gap: 1rem;
}

.chess-board-container {
    display: flex;
    gap: 1rem;
    align-items: center;
}

.overlay {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background-color: rgba(0, 0, 0, 0.5);
    z-index: 999; /* Ensure it's above the board but below the promotion dialog */
}
```

and two diffs are provided above.

### Relevant API Request Output

```shell

```

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by mrubens**
Fixes #2556 by using start line as a hint for where to start searching for diffs, versus previously looking for the chunk specified by start and end line. I think this could have caused incorrectly applied diffs in lots of cases depending on how the LLM interpreted the end line parameter.

This also removes the ability to pass in an empty search block, since we have no way to verify that the line number from the LLM is correct. The model should always be required to pass in a search block.

----

> [!IMPORTANT]
> Disallow empty search content (insertions) in `MultiSearchReplaceDiffStrategy`, remove related tests, and add a fuzzy matching test for issue #2556.
> 
>   - **Behavior change in `multi-search-replace.ts`**:
>     - Disallows empty search content in `MultiSearchReplaceDiffStrategy.applyDiff()`. Now returns an error if search content is empty, removing support for insertions via empty search blocks.
>     - Updates `getSimilarity()` to return 0 for empty search content (was 1).
>   - **Tests in `multi-search-replace.test.ts`**:
>     - Removes all tests for insertions (empty search block with non-empty replace block).
>     - Adds test case for fuzzy matching with slightly off line numbers to reproduce #2556.
>     - Renames test group from "insertion/deletion" to "deletion" to reflect removal of insertion tests.
>   - **No changes to deletion or replacement logic.**
> 
> <sup>This description was created by </sup>[Ellipsis](https://www.ellipsis.dev?ref=RooVetGit%2FRoo-Code&utm_source=github&utm_medium=referral)<sup> for 842bb2b54324c291c7e6ca1ef1edfe83c650341c. It will automatically update as commits are pushed.</sup>

### CODE REVIEW

File: src/core/diff/strategies/multi-search-replace.ts [hunk 1]
```diff
@@ -367,7 +368,6 @@ Only use a single line of '=======' between search and replacement content, beca
 		const replacements = matches
 			.map((match) => ({
 				startLine: Number(match[2] ?? 0),
-				endLine: Number(match[4] ?? resultLines.length),
```
Comment (mrubens) [inline src/core/diff/strategies/multi-search-replace.ts:370]: We're not using the passed in endLine anymore (just taking the start line plus to length of the search block), but I figure we can clean that up as a follow-up if this doesn't cause any unforeseen problems.

**Review by cte — APPROVED** [review]
Makes sense to me!

**Comment by KJ7LNW** [comment]
> The model should always be required to pass in a search block.

I think this means it can no longer modify an empty file. maybe we do not care and that should be the responsibility of write_to_file, but heads up ...

**Comment by mrubens** [comment]
Thanks yeah, that’s what I was thinking

File: src/core/diff/strategies/multi-search-replace.ts (hunk 1 above)
Comment (mrubens) [reply src/core/diff/strategies/multi-search-replace.ts:370]: #2615
