### PR TITLE
fix: prevent duplicate LM Studio models with case-insensitive deduplication

### LINKED ISSUE #6954: LM Studio: Loaded models appear twice in Provider Configuration Profile
### App Version

3.25.10

### API Provider

LM Studio

### Model Used

N/A

### Roo Code Task Links (Optional)

_No response_

### 🔁 Steps to Reproduce

1. Start LM Studio (Windows 11) and load a model to be used with Roo Code
2. Open Roo Code settings -> Providers
3. Add a Configuration Profile with API Provider "LM Studio"
4. The loaded model is displayed twice in the model selection list: once with the model path and once with the model id

Image

### 💥 Outcome Summary

Expected models loaded in LM Studio to appear only once in the Configuration Profile, but got them twice under different names.

### 📄 Relevant Logs or Errors (Optional)

```shell
This might be a bug in getLMStudioModels() (https://github.com/RooCodeInc/Roo-Code/blob/main/src/api/providers/fetchers/lmstudio.ts#L53) where model.path is used as key for downloaded models but model.modelKey is used as key for loaded models.
```

### PR DESCRIPTION
**Pull request by daniel-lxs**
## Summary

This PR fixes the issue where LM Studio models appeared twice in the Provider Configuration Profile when they were both downloaded and loaded. This implementation addresses the feedback from @mechanicmuthu about LM Studio's JIT Model Loading feature.

## Problem

The previous implementation fetched models from two different LM Studio APIs:
- `listDownloadedModels()` - showed all models on disk
- `listLoaded()` - showed models currently in memory

This caused duplicates when a model was both downloaded and loaded, with inconsistent keys (`model.path` vs `model.modelKey`).

## Solution

This PR implements a **case-insensitive deduplication approach** that:
- **Keeps both API calls** to support LM Studio's JIT Model Loading (available since v0.3.5)
- **Deduplicates models** by checking if any existing model key contains the loaded model's identifier (case-insensitive)
- **Prefers loaded model data** when duplicates are found, as it provides more accurate runtime information (contextLength)
- **Maintains compatibility** with JIT loading where models can be automatically loaded on-demand

## Benefits

- ✅ Eliminates duplicates with smart deduplication
- ✅ Supports JIT Model Loading feature (models can be auto-loaded when requested)
- ✅ Shows all available models (both downloaded and loaded)
- ✅ Provides accurate runtime metadata when models are loaded
- ✅ Handles auto-unload after 60-minute timeout gracefully

## Testing

- All existing tests pass
- Added new test case for deduplication logic
- Verified that duplicates are properly handled

## Context

This replaces PR #7141 which only showed loaded models and didn't align with LM Studio's JIT loading capabilities.

Fixes #6954

----

> [!IMPORTANT]
> Implements case-insensitive deduplication in `getLMStudioModels()` to prevent duplicate model entries, preferring loaded models for accurate runtime data.
> 
>   - **Behavior**:
>     - Implements case-insensitive deduplication in `getLMStudioModels()` in `lmstudio.ts` to prevent duplicate model entries.
>     - Prefers loaded model data over downloaded when duplicates are found.
>     - Ensures compatibility with JIT Model Loading by keeping both API calls.
>   - **Testing**:
>     - Adds test cases in `lmstudio.test.ts` for deduplication logic, including path-based matching and distinct name handling.
>     - Verifies that duplicates are properly handled and runtime metadata is accurate.
>   - **Misc**:
>     - Handles auto-unload after 60-minute timeout gracefully.
> 
> <sup>This description was created by </sup>[Ellipsis](https://www.ellipsis.dev?ref=RooCodeInc%2FRoo-Code&utm_source=github&utm_medium=referral)<sup> for 6aba8e562f61bb4e898ac5a939833eca26165384. You can [customize](https://app.ellipsis.dev/RooCodeInc/settings/summaries) this summary. It will automatically update as commits are pushed.</sup>

### CODE REVIEW

File: src/api/providers/fetchers/lmstudio.ts [hunk 1]
```diff
@@ -81,13 +81,37 @@ export async function getLMStudioModels(baseUrl = "http://localhost:1234"): Prom
...
 			return Promise.all(models.map((m) => m.getModelInfo()))
 		})) as Array<LLMInstanceInfo>
 
+		// Deduplicate loaded models - only add if no existing key contains the model's identifier (case-insensitive)
 		for (const lmstudioModel of loadedModels) {
-			models[lmstudioModel.modelKey] = parseLMStudioModel(lmstudioModel)
+			const modelIdentifier = lmstudioModel.modelKey.toLowerCase()
+
+			// Check if any existing model key contains this loaded model's identifier
+			const isDuplicate = Object.keys(models).some(
```
Comment (ghost) [inline src/api/providers/fetchers/lmstudio.ts]: This deduplication logic has a critical flaw - it uses bidirectional substring matching which can cause false positives. For example:
- "llama-3" would incorrectly match "llama-3.1" 
- "mistral" would match "mistral-7b" and "mistral-instruct"

Could we use a more precise matching strategy? Perhaps normalize the model identifiers and use exact matching, or use a more sophisticated comparison that accounts for version numbers?

File: src/api/providers/fetchers/lmstudio.ts [hunk 2]
```diff
@@ -81,13 +81,37 @@ export async function getLMStudioModels(baseUrl = "http://localhost:1234"): Prom
...
+				(existingKey) =>
+					existingKey.toLowerCase().includes(modelIdentifier) ||
+					modelIdentifier.includes(existingKey.toLowerCase()),
+			)
+
+			if (!isDuplicate) {
+				// Use modelKey for loaded models to maintain consistency
+				models[lmstudioModel.modelKey] = parseLMStudioModel(lmstudioModel)
```
Comment (ghost) [inline src/api/providers/fetchers/lmstudio.ts]: Is this intentional? When no duplicate is found, you're using  as the key, but when updating duplicates (line 111), you keep the original key (likely  from downloaded models). This creates inconsistency in how models are keyed in the result object.

Should we standardize on using  for all models to maintain consistency?

File: src/api/providers/fetchers/lmstudio.ts [hunk 3]
```diff
@@ -81,13 +81,37 @@ export async function getLMStudioModels(baseUrl = "http://localhost:1234"): Prom
...
+			} else {
+				// If it's a duplicate, update the existing entry with loaded model info for better context data
+				const existingKey = Object.keys(models).find(
```
Comment (ghost) [inline src/api/providers/fetchers/lmstudio.ts]: Performance concern: This nested loop with substring operations has O(n²) complexity. For users with many models, this could impact performance.

Could we consider using a Map or Set with normalized keys for O(1) lookups? Or at least break early once a duplicate is found?

File: src/api/providers/fetchers/__tests__/lmstudio.test.ts [hunk 4]
```diff
@@ -143,6 +143,50 @@ describe("LMStudio Fetcher", () => {
 			expect(result).toEqual({ [mockRawModel.modelKey]: expectedParsedModel })
 		})
 
+		it("should deduplicate models when both downloaded and loaded", async () => {
```
Comment (ghost) [inline src/api/providers/fetchers/__tests__/lmstudio.test.ts:146]: Good test case! However, could we add more edge cases to ensure robustness? For example:
- Models with similar names ("llama-3" vs "llama-3.1")
- Multiple loaded models with various duplicate scenarios
- Case sensitivity edge cases
- Models with special characters in their paths/keys

**Comment by daniel-lxs** [comment]
Hey @mechanicmuthu, what do you think of this approach?

**Comment by mechanicmuthu** [comment]
Hey @daniel-lxs 
> Hey @mechanicmuthu, what do you think of this approach?

Autoloading of an unloaded model is **working** and tested now by me. 

However, the duplicate issues is there. This is due to different namings here when the model is loaded.

Screenshot 2025-08-18 at 11 10 08 PM

The bottom 2 with simpler names are from currently loaded models, the top 2 are from all models. All 4 work correctly though.

**Comment by fbuechler** [comment]
@daniel-lxs I think the solution requires more complex matching logic because LM Studio seems to adapt the model keys to make them unique if you have different quantizations of the same model downloaded. In that case the key isn't necessarily a substring of the path any more.

Example:
unsloth/Qwen3-4B-Instruct-2507-GGUF/Qwen3-4B-Instruct-2507-UD-Q3_K_XL.gguf -> qwen3-4b-instruct-2507@q3_k_xl
unsloth/Qwen3-4B-Instruct-2507-GGUF/Qwen3-4B-Instruct-2507-UD-Q4_K_XL.gguf -> qwen3-4b-instruct-2507@q4_k_xl

**Comment by daniel-lxs** [comment]
Then I think it would be great to create a properly scoped issue because lm-studio is making it quite hard for us to deduplicate the models.

@mechanicmuthu
@fbuechler

**Comment by fbuechler** [comment]
@daniel-lxs I'm sorry if I'm missing a point here but I don't think it needs to be that hard. In my opinion, the initial PR (https://github.com/RooCodeInc/Roo-Code/pull/6956) provided a simple working solution that consistently used the model's path to prevent duplicate entries and replaced the downloaded model with more details if a loaded model with the same path was found.
