### PR TITLE
fix(ai-sdk): preserve reasoning parts in message conversion

### LINKED ISSUE #11199: AI SDK message conversion loses assistant reasoning/thinking content
### Problem
Assistant reasoning/thinking content is not preserved when messages are converted through the AI SDK message conversion layer.

### Impact
Providers that rely on the AI SDK cannot reliably round-trip reasoning across tool-call turns, and reasoning content may be lost in persisted history.

### Expected behavior
Reasoning/thinking content should be preserved through conversion so it can be carried across turns and persisted without being dropped.

### PR DESCRIPTION
**Pull request by hannesrudolph**
## Problem

When using AI-SDK-backed providers (notably DeepSeek `deepseek-reasoner`) across tool-call turns, the provider may require the assistant's reasoning to be round-tripped (e.g. via `reasoning_content`). We were dropping that reasoning during our Anthropic → AI SDK message conversion, which can cause DeepSeek to reject follow-up requests after a tool call.

Context: DeepSeek “thinking mode” requires returning `reasoning_content` in subsequent requests within the same turn when tool calls are involved.

Closes #11199

### 1) Preserve reasoning through the AI SDK conversion layer

- [`convertToAiSdkMessages()`](src/api/transform/ai-sdk.ts:30) now converts:
  - our stored `{ type: "reasoning", text: string }` content blocks → AI SDK `{ type: "reasoning", text }` parts
  - Anthropic extended thinking blocks `{ type: "thinking", thinking, signature }` → AI SDK `{ type: "reasoning", text }` parts
  - message-level `reasoning_content` (when present) → a canonical AI SDK reasoning part (avoids duplicating with content blocks)

This keeps the AI SDK `ModelMessage` stream complete, so the provider package (e.g. `@ai-sdk/deepseek`) can decide what to send to the native API (including mapping reasoning parts back into `reasoning_content`).

### 2) Store reasoning as structured content in task history (instead of `<think>` tags)

- [`Task.addToApiConversationHistory()`](src/core/task/Task.ts:1015) now persists reasoning as a dedicated first assistant content block (`type: "reasoning"`), rather than embedding `<think>...</think>` into the text.

This enables consistent round-tripping and avoids mixing reasoning into user-visible text.

### 3) Cleanup

- Removed invalid `"openai-compatible"` from the API-provider reasoning allowlist (it is not a `ProviderName`; it’s used for code-index embedding).

## Tests

- Added AI SDK conversion coverage in [`ai-sdk.spec.ts`](src/api/transform/__tests__/ai-sdk.spec.ts:312)
- Updated task history persistence coverage in [`reasoning-preservation.test.ts`](src/core/task/__tests__/reasoning-preservation.test.ts:219)

### CODE REVIEW

**Comment by ghost** [comment]
> **Oroocle**  Clock &nbsp;&nbsp;[See task on Roo Cloud](https://app.roocode.com/cloud-jobs/XgjuTblD?utm_source=github-comment&utm_medium=link&utm_campaign=github.pr.review.sync)

Review status: 1 issue remaining after latest commit.

- [x] Remove/rename the "openai-compatible" entry in the AI-SDK provider allowlist since it is not a valid `ProviderName` and is currently dead code.
- [ ] Preserve `reasoning_content` when `Anthropic.Messages.MessageParam` uses string `content` (currently dropped in `convertToAiSdkMessages`).

> <details>
> <summary>Previous reviews</summary>
> 
> - b0a3feb: [Review #1](https://app.roocode.com/cloud-jobs/7lgs9Dsm?utm_source=previous-reviews&utm_medium=link&utm_campaign=github.pr.review)
> - dc385a4: [Review #2](https://app.roocode.com/cloud-jobs/84x8aBrP?utm_source=previous-reviews&utm_medium=link&utm_campaign=github.pr.review)
> - d29274c: [Review #3](https://app.roocode.com/cloud-jobs/Hohay7Zx?utm_source=previous-reviews&utm_medium=link&utm_campaign=github.pr.review)
> </details>
<sub>Mention @roomote in a comment to request specific changes to this pull request or [fix all unresolved issues](https://app.roocode.com/fix-issues?repo=RooCodeInc/Roo-Code&prNumber=11196&commentId=3849988086).</sub>

File: src/core/task/Task.ts [hunk 1]
```diff
@@ -4564,14 +4564,29 @@ export class Task extends EventEmitter<TaskEvents> implements TaskLike {
...
+						"deepseek",
+						"fireworks",
+						"moonshot",
+						"mistral",
+						"groq",
+						"xai",
+						"cerebras",
+						"sambanova",
+						"huggingface",
+						"openai-compatible",
```
Comment (ghost) [inline src/core/task/Task.ts]: `apiConfiguration.apiProvider` is a `ProviderName`, and "openai-compatible" is not in `providerNames` (it appears to be used for the code index embedder, not as an API provider), so this set membership is effectively dead code; consider removing it or replacing it with the actual providers that need reasoning round-tripped to avoid future confusion.

<sub>[Fix it with Roo Code](https://app.roocode.com/fix-issue/?repo=RooCodeInc/Roo-Code&prNumber=11196&fixId=564e1a9059) or mention @roomote and request a fix.</sub>

File: src/api/transform/ai-sdk.ts [hunk 2]
```diff
@@ -126,6 +126,11 @@ export function convertToAiSdkMessages(
 				}
 			} else if (message.role === "assistant") {
 				const textParts: string[] = []
+				const reasoningParts: string[] = []
+				const reasoningContent = (() => {
```
[the remark this answers is not in the document]
Comment (hannesrudolph) [reply src/api/transform/ai-sdk.ts:130]: This is technically correct, but in practice Task always converts to array format when reasoning is present—see `addToApiConversationHistory()` lines 1074–1091 which prepend a reasoning block and convert string content to `[reasoningBlock, { type: "text", text }]`. So the string-content branch here only handles simple messages that had no reasoning to begin with.

No action needed.

File: src/core/task/Task.ts (hunk 1 above)
Comment (hannesrudolph) [reply src/core/task/Task.ts]: Fixed in 9bf5a39—removed `"openai-compatible"` from the allowlist.

File: src/core/task/Task.ts [hunk 3]
```diff
@@ -4564,14 +4564,28 @@ export class Task extends EventEmitter<TaskEvents> implements TaskLike {
...
 					continue
 				} else if (hasPlainTextReasoning) {
-					// Check if the model's preserveReasoning flag is set
-					// If true, include the reasoning block in API requests
-					// If false/undefined, strip it out (stored for history only, not sent back to API)
-					const shouldPreserveForApi = this.api.getModel().info.preserveReasoning === true
+					// Preserve plain-text reasoning blocks for:
+					// - models explicitly opting in via preserveReasoning
+					// - AI SDK providers (provider packages decide what to include in the native request)
+					const aiSdkProviders = new Set([
```
Comment (mrubens) [inline src/core/task/Task.ts:4570]: Is there a way to figure this out dynamically? I’m worried about forgetting to update this when we add them
