### PR TITLE
fix(ai-sdk): preserve reasoning parts in message conversion

### LINKED ISSUE #11199: AI SDK message conversion loses assistant reasoning/thinking content
### Problem
Assistant reasoning/thinking content is not preserved when messages are converted through the AI SDK message conversion layer.

### Impact
Providers that rely on the AI SDK cannot reliably round-trip reasoning across tool-call turns, and reasoning content may be lost in persisted history.

### Expected behavior
Reasoning/thinking content should be preserved through conversion so it can be carried across turns and persisted without being dropped.

### PR DESCRIPTION
**Pull request by hannesrudolph**
## Problem

When using AI-SDK-backed providers (notably DeepSeek `deepseek-reasoner`) across tool-call turns, the provider may require the assistant's reasoning to be round-tripped (e.g. via `reasoning_content`). We were dropping that reasoning during our Anthropic → AI SDK message conversion, which can cause DeepSeek to reject follow-up requests after a tool call.

Context: DeepSeek “thinking mode” requires returning `reasoning_content` in subsequent requests within the same turn when tool calls are involved.

Closes #11199

### 1) Preserve reasoning through the AI SDK conversion layer

- [`convertToAiSdkMessages()`](src/api/transform/ai-sdk.ts:30) now converts:
  - our stored `{ type: "reasoning", text: string }` content blocks → AI SDK `{ type: "reasoning", text }` parts
  - Anthropic extended thinking blocks `{ type: "thinking", thinking, signature }` → AI SDK `{ type: "reasoning", text }` parts
  - message-level `reasoning_content` (when present) → a canonical AI SDK reasoning part (avoids duplicating with content blocks)

This keeps the AI SDK `ModelMessage` stream complete, so the provider package (e.g. `@ai-sdk/deepseek`) can decide what to send to the native API (including mapping reasoning parts back into `reasoning_content`).

### 2) Store reasoning as structured content in task history (instead of `<think>` tags)

- [`Task.addToApiConversationHistory()`](src/core/task/Task.ts:1015) now persists reasoning as a dedicated first assistant content block (`type: "reasoning"`), rather than embedding `<think>...</think>` into the text.

This enables consistent round-tripping and avoids mixing reasoning into user-visible text.

### 3) Cleanup

- Removed invalid `"openai-compatible"` from the API-provider reasoning allowlist (it is not a `ProviderName`; it’s used for code-index embedding).

## Tests

- Added AI SDK conversion coverage in [`ai-sdk.spec.ts`](src/api/transform/__tests__/ai-sdk.spec.ts:312)
- Updated task history persistence coverage in [`reasoning-preservation.test.ts`](src/core/task/__tests__/reasoning-preservation.test.ts:219)

### CODE REVIEW

File: src/api/transform/ai-sdk.ts [hunk 1]
```diff
@@ -136,21 +141,57 @@ export function convertToAiSdkMessages(
...
 				const content: Array<
+					| { type: "reasoning"; text: string }
 					| { type: "text"; text: string }
 					| { type: "tool-call"; toolCallId: string; toolName: string; input: unknown }
 				> = []
 
+				if (reasoningContent) {
+					content.push({ type: "reasoning", text: reasoningContent })
+				} else if (reasoningParts.length > 0) {
+					content.push({ type: "reasoning", text: reasoningParts.join("") })
```
Comment (ghost) [inline src/api/transform/ai-sdk.ts:192]: Adding `{ type: "reasoning" }` parts here can prevent flattening for providers that require string-only content (for example SambaNova DeepSeek uses a flatten transform), since the flattener only flattens when all parts are `type: "text"`. That can result in sending array content to models that expect a string, causing request failures.

<sub>[Fix it with Roo Code](https://app.roocode.com/fix-issue/?repo=RooCodeInc/Roo-Code&prNumber=11217&fixId=938e94e5db) or mention @roomote and request a fix.</sub>

File: src/core/task/Task.ts [hunk 2]
```diff
@@ -4564,14 +4564,28 @@ export class Task extends EventEmitter<TaskEvents> implements TaskLike {
...
+						"deepseek",
+						"fireworks",
+						"moonshot",
+						"mistral",
+						"groq",
+						"xai",
+						"cerebras",
+						"sambanova",
+						"huggingface",
+					])
```
Comment (ghost) [inline src/core/task/Task.ts]: This `aiSdkProviders` allowlist is doing double duty as a proxy for "providers that need reasoning round-tripped", but it is missing AI SDK providers that also call `convertToAiSdkMessages` (notably `gemini` and `vertex`). That means plain-text reasoning blocks can still be stripped before making a Gemini/Vertex request, even though those providers also emit/consume `reasoning` stream parts. Consider either adding missing providers or keying this off a capability flag (e.g. `usesAiSdk` / protocol) instead of hardcoding names.

<sub>[Fix it with Roo Code](https://app.roocode.com/fix-issue/?repo=RooCodeInc/Roo-Code&prNumber=11217&fixId=f013c069f7) or mention @roomote and request a fix.</sub>
